In [47]:
import pandas as pd
import numpy as np
import streamlit as slt

In [48]:
df = pd.read_csv('incidents.csv')

In [49]:
df.head(5)

,Identifier,Title,Start date,End date,Number of deaths
0,IBD031681,"Food Poisoning, Imo",2025-04-18,2025-04-18,1
1,IBD032064,"Gunmen Kill Man, Benue",2025-03-31,2025-03-31,1
2,IBD032058,"Auto Crash, Lagos",2025-03-31,2025-03-31,1
3,IBD032066,"Stray Bullets, Sokoto",2025-03-31,2025-03-31,1
4,IBD032062,"Lightening Kills Herder, Kaduna",2025-03-30,2025-03-30,1

In [50]:
df[["Incident","State"]]=df["Title"].str.split(",",n=1, expand=True)

In [51]:
df.head(5)

,Identifier,Title,Start date,End date,Number of deaths,Incident,State
0,IBD031681,"Food Poisoning, Imo",2025-04-18,2025-04-18,1,Food Poisoning,Imo
1,IBD032064,"Gunmen Kill Man, Benue",2025-03-31,2025-03-31,1,Gunmen Kill Man,Benue
2,IBD032058,"Auto Crash, Lagos",2025-03-31,2025-03-31,1,Auto Crash,Lagos
3,IBD032066,"Stray Bullets, Sokoto",2025-03-31,2025-03-31,1,Stray Bullets,Sokoto
4,IBD032062,"Lightening Kills Herder, Kaduna",2025-03-30,2025-03-30,1,Lightening Kills Herder,Kaduna

In [52]:
df.isna().sum()

Identifier           0
Title                0
Start date           0
End date             0
Number of deaths     0
Incident             0
State               17
dtype: int64

In [53]:
df=df.drop_duplicates()

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7485 entries, 0 to 7499
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Identifier        7485 non-null   object
 1   Title             7485 non-null   object
 2   Start date        7485 non-null   object
 3   End date          7485 non-null   object
 4   Number of deaths  7485 non-null   int64
 5   Incident          7485 non-null   object
 6   State             7468 non-null   object
dtypes: int64(1), object(6)
memory usage: 467.8+ KB

In [55]:
df=df.drop(columns=['Title'])

In [56]:
df.head(3)

,Identifier,Start date,End date,Number of deaths,Incident,State
0,IBD031681,2025-04-18,2025-04-18,1,Food Poisoning,Imo
1,IBD032064,2025-03-31,2025-03-31,1,Gunmen Kill Man,Benue
2,IBD032058,2025-03-31,2025-03-31,1,Auto Crash,Lagos

In [57]:
df["State"]=df["State"].str.strip()

In [58]:
replace_map={60:"imo",78:"Benue",171:"Edo"}

In [59]:
aso = ['FCT','FCT (Abuja)','FCT, Abuja', 'FCT, (Abuja)','FCT(Abuja)',
'Hamza Musa', 'Vigilantes vs Herders, FCT (Abuja)','Abuja (FCT)','(Fct) Abuja'
]

mask = df['State'].isin(aso)
df.loc[mask, 'State'] = '(FCT) Abuja'

In [60]:
# 📝 Clean and standardize State names by correcting typos, removing variations, 
# and replacing inconsistent entries with their proper names

df['State'] = df['State'].replace(['Rivers (Offshore)','Port Harcourt','Bonny','River'], 'Rivers')
df['State'] = df['State'].replace('Bayelsa (Offshore)', 'Bayelsa')
df['State'] = df['State'].replace('Son, Anambra', 'Anambra')
df['State'] = df['State'].replace('Dies, Ogun', 'Ogun')
df['State'] = df['State'].replace(['Worshipper, Delta', 'n','delta'], 'Delta')
df['State'] = df['State'].replace(['Akwa Ibom (Offshore)', 'Uyo','Akwa Ibom'], 'Akwa Ibom')
df['State'] = df['State'].replace('Ondo, Ondo', 'Ondo')
df['State'] = df['State'].replace(['Katsina 2','Katsina 1',' Katisna','Katisna','Katsina'], 'Katsina')
df['State'] = df['State'].replace(['Nasarwa', 'Nasaraawa'], 'Nasarawa')
df['State'] = df['State'].replace('Bornon', 'Borno')
df['State'] = df['State'].replace(['Jigaawa','Jiagawa','Jigiwa'], 'Jigawa')
df['State'] = df['State'].replace(['Kadauna','Kadun'], 'Kaduna')
df['State'] = df['State'].replace(['Anmabra','ANambra'], 'Anambra')
df['State'] = df['State'].replace('Taraba`', 'Taraba')
df['State'] = df['State'].replace('Katisna', 'Katsina')
df['State'] = df['State'].replace('Zamafara', 'Zamfara')
df['State'] = df['State'].replace('Cross RIvers', 'Cross River')
df['State'] = df['State'].replace('Niger State', 'Niger')

In [61]:
# 📝 Clean specific rows in the 'Incident' column by removing unwanted state names 

df.loc[60, "Incident"] = df.loc[60, "Incident"].replace(". Delta", "").strip()
df.loc[78, "Incident"] = df.loc[78, "Incident"].replace(" Benue", "").strip()
df.loc[171, "Incident"] = df.loc[171, "Incident"].replace(" Edo", "").strip()
df.loc[3888, "Incident"] = df.loc[388, "Incident"].replace(". Edo", "").strip()

In [62]:
df['Start date'] = pd.to_datetime(df['Start date'],format='mixed', errors='coerce')
df['End date'] = pd.to_datetime(df['End date'],format='mixed', errors='coerce')

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7485 entries, 0 to 7499
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Identifier        7485 non-null   object
 1   Start date        7484 non-null   datetime64[ns]
 2   End date          7484 non-null   datetime64[ns]
 3   Number of deaths  7485 non-null   int64
 4   Incident          7485 non-null   object
 5   State             7468 non-null   object
dtypes: datetime64[ns](2), int64(1), object(3)
memory usage: 667.4+ KB

In [64]:
# capitalize each first letter to capital in the state
df['State'] = df['State'].str.title()

In [65]:
df['State'] =df['State'].replace("(Fct) Abuja","(FCT) Abuja")

In [66]:
df['State'] = df['State'].replace(['Abuja','Fct, ( Abuja)','Fct ( Abuja)'], '(FCT) Abuja')
df['State'] = df['State'].replace('Delta2', 'Delta')
df['State'] = df['State'].replace(['Kastina', 'Katisna'], 'Katsina')

In [73]:
asf = df['State'].nunique()
print(asf,"states")

37 states

In [70]:
print(df["State"].unique())

['Imo' 'Benue' 'Lagos' 'Sokoto' 'Kaduna' 'Katsina' 'Plateau' 'Abia'
 'Delta' 'Ogun' 'Gombe' 'Kogi' '(FCT) Abuja' 'Ondo' 'Rivers' 'Kano'
 'Kebbi' 'Edo' 'Ekiti' 'Cross River' 'Anambra' 'Borno' 'Enugu' 'Bauchi'
 'Osun' 'Zamfara' 'Adamawa' None 'Yobe' 'Ebonyi' 'Kwara' 'Jigawa'
 'Nasarawa' 'Akwa Ibom' 'Niger' 'Bayelsa' 'Oyo' 'Taraba' '']

In [72]:
df['State'] = df['State'].astype(str).str.strip()
df = df[~df['State'].isin(['None', ''])]

In [71]:
df.to_csv('Gbemisola.csv')